name: Build Legacy Framework

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Clean
        timeout-minutes: 60
        run: cd ${{ github.workspace }} && find . -mindepth 1 -delete
      - name: Fetch opencv
        timeout-minutes: 60
        run: cd ${{ github.workspace }} && git clone --branch ${{ inputs.ref }} ${{ inputs.repo }} opencv
      - name: Build OpenCV iOS Universal Fat Framework
        timeout-minutes: 120
        run: |
          cd ${{ github.workspace }} && python3 opencv/platforms/ios/build_framework.py ios \
            --iphoneos_archs arm64 --iphonesimulator_archs x86_64 --iphoneos_deployment_target 14.0 \
            --without gpu --without calib3d --without contrib --without features2D --without flann --without highgui --without legacy --without ml --without nonfree --without objdetect --without photo --without stitching --without video --without videostab
      - name: Create Artifact
        timeout-minutes: 10
        run: cd ${{ github.workspace }}/ios && zip -r -9 -y opencv-${{ inputs.ref }}-framework.zip opencv2.framework
      - name: Upload Artifact
        timeout-minutes: 60
        uses: actions/upload-artifact@v4
        with:
          name: opencv-${{ inputs.ref }}-framework.zip
          path: ${{ github.workspace }}/ios/opencv-${{ inputs.ref }}-framework.zip

